#!/bin/sh

#sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 0
#bspc config border_width         4
#bspc config window_gap          12
#bspc config top_padding 25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config active_border_color "#0000ff"
bspc config focused_border_color "#ff00ff"
bspc config normal_border_color "#30302f"

bspc config pointer_follows_monitor true
bspc config pointer_follows_focus false

bspc config remove_disabled_monitors false
bspc config remove_unplugged_monitors false
bspc config merge_overlapping_monitors true

bspc config pointer_modifier mod4

# hide skype pop-out
bspc rule -a Skype hidden=on

# prevents "My people need me!" on albert
bspc rule -a albert border=off state=floating center=true, sticky=on

# tiles reaper midi editor and other windows
bspc rule -a REAPER state=tiled

bspc rule -a albert_hack state=floating border=off
bspc rule -a float state=floating
bspc rule -a full state=fullscreen
bspc rule -a Xmessage state=floating
bspc rule -a Xfce4-appfinder state=fullscreen, layer=above
bspc rule -a Pystopwatch:*:* state=floating, sticky=on
bspc rule -a CapacitorQuest:*:* state=floating
bspc rule -a Dragon-drop state=floating, sticky=on, layer=above
bspc rule -a 'Zathura:*:*' state=tiled

#sh -c "sleep 0.5; bspc wm -o" &

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

#albert &
#feh --bg-fill ~/leti/Pictures/lights_illustration_x4.jpg


# other thingies

#sh -c "find ~/Downloads -maxdepth 1 -type f -mtime +4 -exec rm -rf {} \;" &

